---

name: Course Production Pipeline CI

on:
  push:
    branches:
      - main
      - '[0-9]+-*'

permissions:
  contents: read # for checkout

jobs:
        
  some-job:
    runs-on: ubuntu-latest
    steps:
      - uses: nolar/setup-k3d-k3s@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
